create extension if not exists pgcrypto;

do $$
begin
  create type public.skill_level as enum ('Beg', 'Int', 'Adv');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.player_status as enum ('idle', 'waiting', 'playing');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.court_status as enum ('available', 'open', 'playing');
exception
  when duplicate_object then null;
end $$;

alter type public.court_status add value if not exists 'available' before 'open';

do $$
begin
  create type public.queue_status as enum ('waiting', 'assigned', 'cancelled');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.assignment_status as enum ('playing', 'completed');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  skill_level public.skill_level not null default 'Beg',
  current_status public.player_status not null default 'idle',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint players_name_not_blank check (length(trim(name)) > 0)
);

create unique index if not exists players_name_unique_lower
  on public.players (lower(name));

create table if not exists public.courts (
  id integer generated by default as identity primary key,
  court_number integer not null unique,
  status public.court_status not null default 'available',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.queue_entries (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players(id) on delete cascade,
  status public.queue_status not null default 'waiting',
  joined_at timestamptz not null default now(),
  assigned_at timestamptz,
  cancelled_at timestamptz
);

create unique index if not exists queue_one_waiting_entry_per_player
  on public.queue_entries (player_id)
  where status = 'waiting';

create index if not exists queue_entries_waiting_order
  on public.queue_entries (joined_at)
  where status = 'waiting';

create table if not exists public.court_assignments (
  id uuid primary key default gen_random_uuid(),
  court_id integer not null references public.courts(id) on delete cascade,
  status public.assignment_status not null default 'playing',
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create unique index if not exists court_one_active_assignment
  on public.court_assignments (court_id)
  where status = 'playing';

create table if not exists public.assignment_players (
  assignment_id uuid not null references public.court_assignments(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  primary key (assignment_id, player_id)
);

create table if not exists public.activity_log (
  id uuid primary key default gen_random_uuid(),
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists players_touch_updated_at on public.players;
create trigger players_touch_updated_at
before update on public.players
for each row execute function public.touch_updated_at();

drop trigger if exists courts_touch_updated_at on public.courts;
create trigger courts_touch_updated_at
before update on public.courts
for each row execute function public.touch_updated_at();

drop trigger if exists courts_assign_first_waiting_player on public.courts;
drop function if exists public.assign_first_waiting_player_to_available_court();

alter table public.players enable row level security;
alter table public.courts enable row level security;
alter table public.queue_entries enable row level security;
alter table public.court_assignments enable row level security;
alter table public.assignment_players enable row level security;
alter table public.activity_log enable row level security;

drop policy if exists "public players read" on public.players;
create policy "public players read"
on public.players for select
using (true);

drop policy if exists "public players insert" on public.players;
create policy "public players insert"
on public.players for insert
with check (true);

drop policy if exists "public players update" on public.players;
create policy "public players update"
on public.players for update
using (true)
with check (true);

drop policy if exists "public courts read" on public.courts;
create policy "public courts read"
on public.courts for select
using (true);

drop policy if exists "public courts update" on public.courts;
create policy "public courts update"
on public.courts for update
using (true)
with check (true);

drop policy if exists "public queue read" on public.queue_entries;
create policy "public queue read"
on public.queue_entries for select
using (true);

drop policy if exists "public queue insert" on public.queue_entries;
create policy "public queue insert"
on public.queue_entries for insert
with check (true);

drop policy if exists "public queue update" on public.queue_entries;
create policy "public queue update"
on public.queue_entries for update
using (true)
with check (true);

drop policy if exists "public assignments read" on public.court_assignments;
create policy "public assignments read"
on public.court_assignments for select
using (true);

drop policy if exists "public assignments insert" on public.court_assignments;
create policy "public assignments insert"
on public.court_assignments for insert
with check (true);

drop policy if exists "public assignments update" on public.court_assignments;
create policy "public assignments update"
on public.court_assignments for update
using (true)
with check (true);

drop policy if exists "public assignment players read" on public.assignment_players;
create policy "public assignment players read"
on public.assignment_players for select
using (true);

drop policy if exists "public assignment players insert" on public.assignment_players;
create policy "public assignment players insert"
on public.assignment_players for insert
with check (true);

drop policy if exists "public activity read" on public.activity_log;
create policy "public activity read"
on public.activity_log for select
using (true);

drop policy if exists "public activity insert" on public.activity_log;
create policy "public activity insert"
on public.activity_log for insert
with check (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'players'
  ) then
    alter publication supabase_realtime add table public.players;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'courts'
  ) then
    alter publication supabase_realtime add table public.courts;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'queue_entries'
  ) then
    alter publication supabase_realtime add table public.queue_entries;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'court_assignments'
  ) then
    alter publication supabase_realtime add table public.court_assignments;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'assignment_players'
  ) then
    alter publication supabase_realtime add table public.assignment_players;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'activity_log'
  ) then
    alter publication supabase_realtime add table public.activity_log;
  end if;
end $$;

-- Book Court screen tables and columns.
-- This section supports the Expo Book tab directly:
-- players_queue, courts with Available/Occupied state, and match_history.

drop trigger if exists courts_assign_first_waiting_player on public.courts;
drop function if exists public.assign_first_waiting_player_to_available_court();

alter table public.courts
  alter column status drop default;

alter table public.courts
  alter column status type text
  using case
    when lower(status::text) in ('available', 'open') then 'Available'
    when lower(status::text) in ('occupied', 'playing') then 'Occupied'
    else 'Available'
  end;

alter table public.courts
  add column if not exists assigned_player_ids uuid[] not null default '{}',
  add column if not exists assigned_player_names text[] not null default '{}',
  add column if not exists match_started_at timestamptz,
  add column if not exists match_duration_minutes integer not null default 20;

update public.courts
set status = case
  when lower(status) in ('available', 'open') then 'Available'
  when lower(status) in ('occupied', 'playing') then 'Occupied'
  else 'Available'
end;

alter table public.courts
  alter column status set default 'Available';

alter table public.courts
  drop constraint if exists courts_status_check;

alter table public.courts
  add constraint courts_status_check
  check (status in ('Available', 'Occupied'));

insert into public.courts (court_number, status)
values
  (1, 'Available'),
  (2, 'Available'),
  (3, 'Available'),
  (4, 'Available')
on conflict (court_number) do nothing;

create table if not exists public.players_queue (
  id uuid primary key default gen_random_uuid(),
  player_name text not null,
  skill_level text not null default 'Beg',
  status text not null default 'waiting',
  court_id integer references public.courts(id) on delete set null,
  match_group_id uuid,
  created_at timestamptz not null default now(),
  assigned_at timestamptz,
  finished_at timestamptz,
  constraint players_queue_name_not_blank check (length(trim(player_name)) > 0),
  constraint players_queue_skill_check check (skill_level in ('Beg', 'Int', 'Adv')),
  constraint players_queue_status_check check (status in ('waiting', 'playing', 'done'))
);

create index if not exists players_queue_waiting_order
  on public.players_queue (created_at)
  where status = 'waiting';

create index if not exists players_queue_status_idx
  on public.players_queue (status);

create table if not exists public.match_history (
  id uuid primary key default gen_random_uuid(),
  court_id integer references public.courts(id) on delete set null,
  court_number integer,
  team_a_players text[] not null default '{}',
  team_b_players text[] not null default '{}',
  team_a_score integer not null,
  team_b_score integer not null,
  winner text not null default 'Draw',
  match_date date not null default current_date,
  match_started_at timestamptz,
  match_ended_at timestamptz,
  played_at timestamptz not null default now(),
  constraint match_history_scores_not_negative check (team_a_score >= 0 and team_b_score >= 0),
  constraint match_history_winner_check check (winner in ('Team A', 'Team B', 'Draw'))
);

alter table public.match_history
  add column if not exists court_number integer,
  add column if not exists winner text not null default 'Draw',
  add column if not exists match_date date not null default current_date,
  add column if not exists match_started_at timestamptz,
  add column if not exists match_ended_at timestamptz;

update public.match_history
set winner = 'Draw'
where winner is null;

update public.match_history
set match_date = played_at::date
where match_date is null;

alter table public.match_history
  alter column winner set default 'Draw',
  alter column winner set not null,
  alter column match_date set default current_date,
  alter column match_date set not null;

alter table public.match_history
  drop constraint if exists match_history_winner_check;

alter table public.match_history
  add constraint match_history_winner_check
  check (winner in ('Team A', 'Team B', 'Draw'));

create index if not exists match_history_played_at_idx
  on public.match_history (played_at desc);

alter table public.players_queue enable row level security;
alter table public.match_history enable row level security;

drop policy if exists "public players queue read" on public.players_queue;
create policy "public players queue read"
on public.players_queue for select
using (true);

drop policy if exists "public players queue insert" on public.players_queue;
create policy "public players queue insert"
on public.players_queue for insert
with check (true);

drop policy if exists "public players queue update" on public.players_queue;
create policy "public players queue update"
on public.players_queue for update
using (true)
with check (true);

drop policy if exists "public players queue delete" on public.players_queue;
create policy "public players queue delete"
on public.players_queue for delete
using (true);

drop policy if exists "public match history read" on public.match_history;
create policy "public match history read"
on public.match_history for select
using (true);

drop policy if exists "public match history insert" on public.match_history;
create policy "public match history insert"
on public.match_history for insert
with check (true);

drop policy if exists "public match history delete" on public.match_history;
create policy "public match history delete"
on public.match_history for delete
using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'players_queue'
  ) then
    alter publication supabase_realtime add table public.players_queue;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'match_history'
  ) then
    alter publication supabase_realtime add table public.match_history;
  end if;
end $$;
